-- supabase/migrations/20250825112617_consolidated_waitlist.sql

-- Create waitlist table if it doesn't exist to protect existing data
create table if not exists
  public.waitlist (
    id bigint generated by default as identity,
    email text not null,
    created_at timestamp with time zone not null default now(),
    constraint waitlist_pkey primary key (id),
    constraint waitlist_email_key unique (email)
  ) tablespace pg_default;

-- The old webhook and trigger were removed in a later migration (20250825130000),
-- so we won't include them here to reflect the final state.

-- Enable Row Level Security if not already enabled
-- Using a DO block to check if RLS is already enabled
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'waitlist' AND rowsecurity) THEN
    ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;
  END IF;
END
$$;

-- Drop existing policies before creating new ones to avoid errors on re-run
DROP POLICY IF EXISTS "Allow public insert" ON public.waitlist;
DROP POLICY IF EXISTS "Allow public read access" ON public.waitlist;

-- Create a policy to allow public insertion
create policy "Allow public insert" on public.waitlist for insert
with
  check (true);

-- Create a policy to allow public read access
CREATE POLICY "Allow public read access"
ON public.waitlist
FOR SELECT
USING (true);

-- Grant usage on schema and select on table to anon role
grant usage on schema public to anon;
grant select on table public.waitlist to anon;
