import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { withEntitlements } from "../_shared/rbac.ts";
import { corsHeaders } from "../_shared/cors.ts";
import { getLanguage } from "../_shared/prompts.ts";
import { getGeminiClient } from "../_shared/gemini-client.ts";

// Enhanced interfaces based on plan specifications
interface TranscriptionSegment {
  id: string;
  rawText: string;
  timestamp: number;
  sourceType: "microphone" | "system";
}

interface SessionContext {
  sessionId: string;
  conversationHistory: string[];
  userLanguage: string;
}

interface EnhanceRequest {
  segments: TranscriptionSegment[];
  sessionContext: SessionContext;
}

interface EnhancedSegment {
  id: string;
  corrected: string;
  translation?: string;
  intention: {
    primary: "question" | "command" | "statement" | "schedule" | "reminder" | "concern" | "request";
    confidence: number;
    suggestedActions?: string[];
  };
  keywords?: string[];
  confidence: number;
}

interface EnhanceResponse {
  segments: EnhancedSegment[];
  processingTime: number;
  errors?: Array<{ segmentId: string; error: string }>;
}

// Enhanced prompts for transcription improvement
const TRANSCRIPTION_ENHANCEMENT_PROMPTS = {
  en: {
    base: ({
      rawText,
      conversationHistory,
      userLanguage,
    }: {
      rawText: string;
      conversationHistory: string[];
      userLanguage: string;
    }) => `You are a transcription enhancement assistant. You will be given a raw transcription generated by an STT model and conversation history for context. The wording might be wrong due to similar pronunciation, so use context to correct words.

Your task is to enhance the transcription by:
1. **Correct**: Fix grammar, punctuation, wording, spelling
2. **Contextualize**: Use conversation history for coherence
3. **Detect Intent**: Identify primary intention and confidence
4. **Extract Keywords**: Technical/specialized terms only

CONVERSATION HISTORY:
${conversationHistory.length > 0 ? conversationHistory.join('\n') : 'No previous context'}

RAW TRANSCRIPTION: "${rawText}"
USER LANGUAGE: ${userLanguage}

Return ONLY valid JSON with this exact structure:
{
  "corrected": "Enhanced and corrected transcription text",
  "translation": "Translation if different from userLanguage, otherwise null",
  "intention": {
    "primary": "question|command|statement|schedule|reminder|concern|request",
    "confidence": 0.95,
    "suggestedActions": ["ai-action-answer", "ai-action-schedule"]
  },
  "keywords": ["technical", "terms", "only"],
  "confidence": 0.95
}`,
  },
  "zh-TW": {
    base: ({
      rawText,
      conversationHistory,
      userLanguage,
    }: {
      rawText: string;
      conversationHistory: string[];
      userLanguage: string;
    }) => `你是一個轉錄增強助理。你會收到STT模型產生的原始轉錄和對話歷史作為上下文。用字可能因發音相似而錯誤，請利用上下文來修正單詞。

你的任務是透過以下方式增強轉錄：
1. **修正**: 修正語法、標點符號、用字、拼寫
2. **語境化**: 使用對話歷史來確保連貫性
3. **偵測意圖**: 識別主要意圖和信心度
4. **提取關鍵字**: 僅限技術/專業術語

對話歷史：
${conversationHistory.length > 0 ? conversationHistory.join('\n') : '無先前上下文'}

原始轉錄：「${rawText}」
使用者語言：${userLanguage}

僅回傳有效的JSON，結構如下：
{
  "corrected": "增強和修正後的轉錄文字",
  "translation": "如果與使用者語言不同則翻譯，否則為null",
  "intention": {
    "primary": "question|command|statement|schedule|reminder|concern|request",
    "confidence": 0.95,
    "suggestedActions": ["ai-action-answer", "ai-action-schedule"]
  },
  "keywords": ["技術", "術語", "僅限"],
  "confidence": 0.95
}`,
  },
};


// Process individual segment
async function enhanceSegment(
  segment: TranscriptionSegment,
  sessionContext: SessionContext,
  geminiClient: any
): Promise<EnhancedSegment> {
  const lang = getLanguage(sessionContext.userLanguage);
  const prompt = TRANSCRIPTION_ENHANCEMENT_PROMPTS[lang].base({
    rawText: segment.rawText,
    conversationHistory: sessionContext.conversationHistory,
    userLanguage: sessionContext.userLanguage,
  });

  try {
    // Use shared Gemini client with JSON parsing
    const { data: enhancementData } = await geminiClient.generateJSON(prompt, {
      temperature: 0.1,
      maxOutputTokens: 1024,
    });

    // Validate and sanitize response
    const enhancedSegment: EnhancedSegment = {
      id: segment.id,
      corrected: enhancementData.corrected || segment.rawText,
      translation: enhancementData.translation || undefined,
      intention: {
        primary: enhancementData.intention?.primary || "statement",
        confidence: Math.min(Math.max(enhancementData.intention?.confidence || 0.5, 0), 1),
        suggestedActions: enhancementData.intention?.suggestedActions || [],
      },
      keywords: Array.isArray(enhancementData.keywords) ? enhancementData.keywords : [],
      confidence: Math.min(Math.max(enhancementData.confidence || 0.5, 0), 1),
    };

    return enhancedSegment;
  } catch (error) {
    console.error(`Failed to enhance segment ${segment.id}:`, error.message);
    // Return fallback enhancement
    return {
      id: segment.id,
      corrected: segment.rawText,
      intention: {
        primary: "statement",
        confidence: 0.3,
        suggestedActions: [],
      },
      keywords: [],
      confidence: 0.3,
    };
  }
}

const handleRequest = async (req: Request, profile: Record<string, any>) => {
  const startTime = Date.now();

  try {
    console.log(`[transcription-enhance] function invoked at: ${new Date().toISOString()}`);

    const { segments, sessionContext }: EnhanceRequest = await req.json();

    if (!segments || !Array.isArray(segments) || segments.length === 0) {
      return new Response(JSON.stringify({ error: "Segments array is required and cannot be empty" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!sessionContext || !sessionContext.sessionId) {
      return new Response(JSON.stringify({ error: "Session context with sessionId is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Initialize shared Gemini client
    const geminiClient = getGeminiClient({
      temperature: 0.1,
      topK: 1,
      topP: 0.8,
      maxOutputTokens: 1024,
    });

    // Process segments in parallel with error handling
    const enhancementPromises = segments.map(async (segment) => {
      try {
        return await enhanceSegment(segment, sessionContext, geminiClient);
      } catch (error) {
        console.error(`Error processing segment ${segment.id}:`, error.message);
        return {
          segmentId: segment.id,
          error: error.message,
        };
      }
    });

    const results = await Promise.all(enhancementPromises);

    // Separate successful enhancements from errors
    const enhancedSegments: EnhancedSegment[] = [];
    const errors: Array<{ segmentId: string; error: string }> = [];

    results.forEach((result) => {
      if ('error' in result) {
        errors.push(result as { segmentId: string; error: string });
      } else {
        enhancedSegments.push(result as EnhancedSegment);
      }
    });

    const processingTime = Date.now() - startTime;

    const response: EnhanceResponse = {
      segments: enhancedSegments,
      processingTime,
      ...(errors.length > 0 && { errors }),
    };

    console.log(`[transcription-enhance] processed ${segments.length} segments in ${processingTime}ms`);

    return new Response(JSON.stringify(response), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("[transcription-enhance] error:", error.message);

    const processingTime = Date.now() - startTime;

    return new Response(JSON.stringify({
      error: "Internal Server Error",
      processingTime,
      details: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
};

const transcriptionEnhanceHandler = withEntitlements(
  "allow_ai_action:transcription_enhance",
  "daily_ai_action:transcription_enhance_calls",
  handleRequest,
);

serve(transcriptionEnhanceHandler);